### ISSUE TITLE
PHP Fatal Error

### ISSUE THREAD

**Issue by vik0803** [xumes/xumes-project-management#1]
Hi,

I was reviewing your project and seems that it would be interesting to work on so I tried to deploy the same but receiving error as below.

```
PHP Fatal error:  Class 'CodeProject\Console\ConsoleKernel' not found in /var/www/html/xumes/app/Console/Kernel.php on line 7
Script php artisan clear-compiled handling the pre-update-cmd event returned with error code 255

```

Appreciate your help on the same.

Thanks,
Vik

**Comment by xumes** [comment]
Hello Vik, 

I have refactored the app trying to fix this issue. Would you like to try to deploy it again?

**Comment by vik0803** [comment]
There is still an error

> php artisan clear-compiled
> PHP Fatal error:  Uncaught exception 'ReflectionException' with message 'Class CodeProject\Console\Kernel does not exist' in /var/www/html/xumes/vendor/laravel/framework/src/Illuminate/Container/Container.php:734

**Comment by vik0803** [comment]
Seems to me that there is still some more correction needed but it looks that we are reaching destination.

:)

Thanks,
Vik

**Comment by vik0803** [comment]
Hi,

Did you got a chance to update the repository so that I can try it out today. 

Thanks,
